name: BookDiseases
main: me.drbooker.diseases.Diseases
version: 1.0
api-version: 1.15
commands:
  leki:
    description: "Glowna komenda pluginu BookDiseases"

permissions:
  leki.*:
    default: op
    children:
      leki.reload: true